### ISSUE TITLE
Add a copy button to output

### ISSUE THREAD

**Issue by Hona** [AwesomeBlazor/AutoScrum#59]
As per my conversation with @bradystroud,

- [x] Add a copy button for the whole output
- [ ] Add a copy button for a single user - ensure it is separate from the report for copy/paste's sake - popover?

**Comment by bradystroud** [comment]
This package should make implementation easy
https://github.com/Append-IT/Blazor.Clipboard

**Comment by jernejk** [comment]
Because we want rich text editing, I implemented my own JS script for this feature.

**Comment by jernejk** [comment]
![image](https://user-images.githubusercontent.com/5943653/155829396-cb744803-e37f-498e-a2ea-291947759a42.png)

![image](https://user-images.githubusercontent.com/5943653/155829399-0e0040c4-e723-4ed9-a381-a00642650d28.png)

![image](https://user-images.githubusercontent.com/5943653/155829415-0f590a26-8a05-4eb7-a3b1-97b8c6e9627c.png)
